name: "Plantuml Install Action"
description: "Install Plantuml to Reasonably Standard Place for Usage"
inputs:
  plantuml_version:
    description: Which version of Plantuml To Use
    required: false
    default: latest
  install_java:
    description: Should I Install a JRE for you too?
    required: false
    default: no
  install_dot:
    description: Should I Install a Graphviz for you too?
    required: false
    default: no
runs:
  using: "composite"
  steps:
    - name: JQ Dependency
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: jq autoconf libtool

    - name: Download Plantuml
      run: |
        mkdir -p /opt/plantuml/
        if [[ ${plantuml_version} == "latest" ]] ; then
          version=$(curl -ks https://api.github.com/repos/plantuml/plantuml/releases/latest | jq -r '.tag_name')
          echo -e "Latest Version detected as ${version}"
        else
          echo -e "Explicit Version"
          version="${plantuml_version}"
        fi
        
        dwd_url=$(curl -ks https://api.github.com/repos/plantuml/plantuml/releases/tags/${version} | jq -r '.assets | map(select(.name == "plantuml.jar"))[0].browser_download_url')
        echo -e "Downloading Plantuml Version ${version} from ${dwd_url}"
        
        wget -O /opt/plantuml/plantuml.jar "${dwd_url}"
      env:
        plantuml_version: ${{ inputs.plantuml_version }}
      shell: bash



    - name: Download Plantuml Script
      run: |
        plantuml_script="https://raw.githubusercontent.com/chalbersma/plantuml-install-action/main/dist/plantuml"
        mkdir -p /opt/plantuml/bin
        curl -o /opt/plantuml/bin/plantuml "${plantuml_script}"
        chmod +x /opt/plantuml/bin/plantuml
        echo "/opt/plantuml/bin/" >> $GITHUB_PATH
      shell: bash

    - name: Install java
      uses: awalsh128/cache-apt-pkgs-action@v1
      if: "${{ inputs.install_java == 'yes' }}"
      with:
        packages: default-jre-headless libfop-java libbatik-java libjlatexmath-java libavalon-framework-java libcommons-io-java libcommons-logging-java libxml-commons-external-java libxmlgraphics-commons-java

    - name: Install Dot
      if: "${{ inputs.install_dot == 'yes' }}"
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: graphviz ditaa